apps/clinic/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from .views import (BookTimeCreateView, ClinicView, BookTimeListView,
                    ReservationServiceCreateView, ReservationImageCreateView,
                    ReservationMedicineCreateView, ServiceListView,
                    BrandCompanyListView, BrandListView, MedicineListView,
                    IllnessListView, IllnessCreateView, IllnessUpdateView,
                    ServiceCreateView, ServiceUpdateView, BrandCompanyCreateView,
                    BrandCompanyUpdateView, BrandCreateView, BrandUpdateView,
                    MedicineCreateView, MedicineUpdateView, ReservationImageUpdateView,
                    ReservationImageDeleteView,
)

app_name = 'clinic'

urlpatterns = [
    path('_book_time_create/', BookTimeCreateView.as_view(), name='book_time_create'),
    path('', ClinicView.as_view(), name='clinic'),
    path('book-times/', BookTimeListView.as_view(), name='book_time_list'),
    path('reservation/<pk>/new-service/', ReservationServiceCreateView.as_view(), name='new_service'),
    path('reservation/<pk>/new-image/', ReservationImageCreateView.as_view(), name='new_image'),
    path('reservation/<pk>/update-image/', ReservationImageUpdateView.as_view(), name='update_image'),
    path('reservation/<pk>/update-image/', ReservationImageDeleteView.as_view(), name='delete_image'),
    path('reservation/<pk>/new-medicine/', ReservationMedicineCreateView.as_view(), name='new_medicine'),
    path('illnesses/', IllnessListView.as_view(), name='illness_list'),
    path('illnesses/new/', IllnessCreateView.as_view(), name='new_illness'),
    path('illnesses/<pk>/update/', IllnessUpdateView.as_view(), name='update_illness'),
    path('services/', ServiceListView.as_view(), name='service_list'),
    path('services/new/', ServiceCreateView.as_view(), name='new_service'),
    path('services/<pk>/update/', ServiceUpdateView.as_view(), name='update_service'),
    path('companies/', BrandCompanyListView.as_view(), name='brand_company_list'),
    path('companies/new/', BrandCompanyCreateView.as_view(), name='new_brand_company'),
    path('companies/<pk>/update/', BrandCompanyUpdateView.as_view(), name='update_brand_company'),
    path('brands/', BrandListView.as_view(), name='brand_list'),
    path('brands/new/', BrandCreateView.as_view(), name='new_brand'),
    path('brands/<pk>/update/', BrandUpdateView.as_view(), name='update_brand'),
    path('medicines/', MedicineListView.as_view(), name='medicine_list'),
    path('medicines/new/', MedicineCreateView.as_view(), name='new_medicine'),
    path('medicines/<pk>/update/', MedicineUpdateView.as_view(), name='update_medicine'),
]

apps/users/auth/urls.py
from django.urls import path
from django.contrib.auth import views as auth
from .views import StaffLoginView, StaffForgetPasswordView, StaffNewPasswordView

urlpatterns = [
    path('staff/login/', StaffLoginView.as_view(), name='staff_login'),
    path('staff/forgot-password/', StaffForgetPasswordView.as_view(), name='staff_forget_password'),
    path('staff/new-password/', StaffNewPasswordView.as_view(), name='password_reset_confirm'),
    path('logout/', auth.LogoutView.as_view(), name='account_logout'),
]

apps/users/urls.py
from django.urls import include, path
from apps.users.views import (
    DashboardView, ProfileUpdateView, PatientCreateView, PatientDetailView,
    PatientListView, PatientEditView, UserListView, UserUpdateView,
    UserCreateView, UserSetPasswordView,
)


app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('new/', UserCreateView.as_view(), name='new_user'),
    path('<pk>/update/', UserUpdateView.as_view(), name='update_user'),
    path('<pk>/set-password/', UserSetPasswordView.as_view(), name='set_password'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('profile/', DashboardView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='update_profile'),
    path('auth/', include('apps.users.auth.urls')),
    path('patients/', PatientListView.as_view(), name='patient_list'),
    path('patients/new/', PatientCreateView.as_view(), name='patient_create'),
    path('patients/<pk>/', PatientDetailView.as_view(), name='patient_details'),
    path('patients/<pk>/edit/', PatientEditView.as_view(), name='patient_edit'),
]

ghahri/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('d/admin/', admin.site.urls),
    path('clinic/', include('apps.clinic.urls')),
    path('core/', include('apps.core.urls')),
    path('users/', include('apps.users.urls')),
    path('auth/', include('apps.users.auth_urls')),
    path('api/', include('apps.clinic.api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/views.py
from urllib import request
from django.contrib.auth import update_session_auth_hash
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy as _
from django.views.generic import View, ListView, CreateView, UpdateView, TemplateView, FormView
from jalali_date import date2jalali, datetime2jalali
from apps.core.permissions import PermissionRequireMixin, Permissions
from apps.core.base import BaseContextMixin, GenericFormView, GenericModelFormView
from apps.core.mixins import CustomFormTemplateMixin, CustomListTemplateMixin
from .forms import (
    PatientForm, UserForm, PatientFilterForm, UserSignUpForm, UserProfileForm,
    UserUpdateForm, UserSetPasswordForm
)
User = get_user_model()


class DashboardView(LoginRequiredMixin, BaseContextMixin, View):
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return render(request, 'users/dashboard.html', context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ProfileUpdateView(LoginRequiredMixin, GenericModelFormView):
    model = User
    form_class = UserProfileForm
    template_name = 'generic_model_form.html'
    success_url = reverse_lazy('users:dashboard')
    success_message = 'اطلاعات شما با موفقیت بروزرسانی شد.'

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['extra_scripts'] = ['users/scripts/career_dropdown.js']
        return context

        
class UserListView(CustomListTemplateMixin, PermissionRequireMixin, ListView):
    permissions = [User.Roles.DOCTOR, User.Roles.ADMIN]
    page_title = 'لیست کاربران'
    queryset = User.objects.filter(role__in=[User.Roles.DOCTOR, User.Roles.SECRETARY, User.Roles.ADMIN])
    context_object_name = 'users'
    paginate_by = 100
    ordering = '-created_at'
    fields = ['username', 'first_name', 'last_name', 'role', 'created_at', 'last_login']
    header_buttons = [{'title': 'افزودن کاربر', 'url': reverse_lazy('users:new_user')}]
    action_buttons = [
        {'title': 'ویرایش', 'url_name': 'users:update_user', 'arg_field': 'id',
         'fa-icon': 'fa-edit', 'class': '', 'class_form_field': 'id'},
        {'title': 'تغییر رمز', 'url_name': 'users:set_password', 'arg_field': 'id',
         'fa-icon': 'fa-edit', 'class': 'btn-warning', 'class_form_field': 'id'},
    ]

    def get_role(self, obj):
        return obj.get_role_display()

    def get_created_at(self, obj):
        return datetime2jalali(obj.created_at).strftime('%Y/%m/%d %H:%M:%S')

    def get_last_login(self, obj):
        last_login = obj.last_login
        if last_login:
            return datetime2jalali(last_login).strftime('%Y/%m/%d %H:%M:%S')
        return '-'


class UserCreateView(CustomFormTemplateMixin, PermissionRequireMixin, CreateView):
    permissions = [User.Roles.DOCTOR, User.Roles.ADMIN]
    model = User
    form_class = UserForm
    page_title = 'افزودن کاربر جدید'
    success_url = reverse_lazy('users:user_list')
    cancel_url = reverse_lazy('users:user_list')
    success_message = ' کاربر جدید با موفقیت ثبت شد.'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.username = user.mobile
        user.save()
        return super().form_valid(form)



class UserUpdateView(UserCreateView, UpdateView):
    page_title = 'ویرایش کاربر'
    success_message = 'کاربر با موفقیت ویرایش شد.'
    form_class = UserUpdateForm

    def get_success_url(self) -> str:
        return reverse_lazy('clinic:clinic')

    def get_queryset(self):
        return User.objects.filter(pk=self.request.user.id)


class UserSetPasswordView(CustomFormTemplateMixin, PermissionRequireMixin, FormView):
    model = User
    form_class = UserSetPasswordForm
    success_url = reverse_lazy('clinic:clinic')
    success_message = 'رمز عبور با موفقیت بروزرسانی شد.'
    page_title = 'تغییر رمز عبور'

    def get_form_kwargs(self):
        kwargs = super(UserSetPasswordView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def get_page_subtitle(self):
        user = self.get_object()
        return user.get_full_name()      

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return get_object_or_404(User, pk=pk)
    
    def form_valid(self, form):
        user = self.get_object()
        user.set_password(form.cleaned_data['password'])
        update_session_auth_hash(self.request, user)
        user.save()
        return super().form_valid(form)


class PatientCreateView(CustomFormTemplateMixin, PermissionRequireMixin, CreateView):
    permissions = [User.Roles.SECRETARY, User.Roles.DOCTOR, User.Roles.ADMIN]
    model = User
    form_class = PatientForm
    success_url = reverse_lazy('users:patient_list')
    success_message = 'اطلاعات با موفقیت ثبت شد.'
    page_title = 'افزودن پرونده جدید'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['extra_scripts'] = ['users/scripts/career_dropdown.js']
        return context

    def form_valid(self, form):
        form.instance.role = User.Roles.PATIENT
        messages.success(self.request, self.success_message)
        return super().form_valid(form)


class PatientEditView(CustomFormTemplateMixin, PermissionRequireMixin, UpdateView):
    permissions = [User.Roles.SECRETARY, User.Roles.DOCTOR, User.Roles.ADMIN]
    model = User
    form_class = PatientForm
    success_url = reverse_lazy('users:patient_list')
    success_message = 'اطلاعات با موفقیت بروزرسانی شد.'
    page_title = 'ویرایش پرونده'

    def form_valid(self, form):
        messages.success(self.request, self.success_message)
        return super().form_valid(form)


class PatientListView(CustomListTemplateMixin, PermissionRequireMixin, ListView):
    permissions = [User.Roles.SECRETARY, User.Roles.DOCTOR, User.Roles.ADMIN]
    template_name = 'generic_model_list.html'
    context_object_name = 'patients'
    page_title = "لیست بیماران"
    fields = ['first_name', 'last_name', 'mobile', ]
    header_buttons = [
        {'title': 'افزودن بیمار', 'url': reverse_lazy('users:patient_create'), 'fa-icon': 'fa-plus', 'class': 'btn-success'},
    ]
    action_buttons = [
        {'title': 'مشاهده پرونده', 'url_name': 'users:patient_details', 'arg_field': 'id',
         'fa-icon': 'fa-list', 'class': '', 'class_form_field': 'id'},
        {'title': 'ویرایش', 'url_name': 'users:patient_edit', 'arg_field': 'id',
         'fa-icon': 'fa-list', 'class': '', 'class_form_field': 'id'},
    ]
    paginate_by = None
    filter_class = PatientFilterForm

    def get_queryset(self):
        objects = User.objects.filter(role=User.Roles.PATIENT)
        filtered_objects = self.filter_class(self.request.GET, queryset=objects)
        return filtered_objects.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class PatientDetailView(PermissionRequireMixin ,TemplateView):
    permissions = [User.Roles.DOCTOR, User.Roles.ADMIN, User.Roles.SECRETARY]
    template_name = 'users/patient_detail_view.html'
    context_object_name = 'patient'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        patient = get_object_or_404(User, id=kwargs['pk'])
        context["patient"] = patient
        return context

apps/users/templates/users/components/image_gallery.html
<div class="timeline-image-gallery">
    {% for img in images %}
        <div class="image-container">
            <div class="header">
                <h5>{{img.get_capture_time_display}}</h5>
                <div class="actions">
                    <a href="{% url 'clinic:update_image' img.id %}" class="btn btn-primary btn-sm">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <a href="{% url 'clinic:delete_image' img.id %}" class="btn btn-danger btn-sm">
                        <i class="fa fa-trash"></i>
                    </a>
                </div>
            </div>
            <div class="body">
                <a href="{{img.image.url}}" target="_blank" 
                    style="background-image: url('{{img.image_thumbnail.url}}')">
                </a>
            </div>
            {% if img.description %}
                <div class="footer">
                    <p>{{img.description}}</p>
                </div>
            {% endif %}
        </div>
    {% empty %}
        <p class="empty-result">هیچ تصویری وجود ندارد</p>
    {% endfor %}
</div>

apps/users/templates/users/components/reservation_history.html
{% load jalali_tags humanize %}

<div class="treatment-history">
    <div class="timeline">
        {% for reservation in reservations %}
            <div class="timeline-container">
                <div class="timeline-icon">
                    <i class="far fa-grin-beam-sweat"></i>
                </div>
                <div class="timeline-body reservation" data-id={{reservation.id}}>
                    <div class="timeline-card-header">
                        <h4 class="timeline-title">
                            {{reservation.book_time.date|to_jalali:"%Y/%m/%d"}} ساعت
                            {{reservation.book_time.get_time_in_day_display}}
                            <small>تاریخ ویزیت: {{reservation.visited_at|to_jalali:"%Y/%m/%d %H:%M:%S"}}</small>
                        </h4>
                        <span class="timeline-price">{{reservation.total_price|intcomma:False}} تومان</span>
                    </div>
                    <div class="timeline-card-body">
                        <div id="services">
                            <table>
                                <thead>
                                    <tr>
                                        <th colspan="4" class="colspan">سرویس‌ها</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for service in reservation.services.all %}
                                        <tr>
                                            <td>{{service.service_name}}</td>
                                            <td>{{service.final_price|intcomma:False}} تومان</td>
                                            <td>{{service.brand}}</td>
                                            <td>{{service.amount}}</td>
                                        </tr>
                                        {% if service.description %}
                                        <tr><td colspan="4" class="colspan">{{service.description}}</td>
                                        {% endif %}
                                    {% empty %}
                                        <tr><td colspan="4" class="colspan">هیچ سرویسی وجود ندارد</td></tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div id="medicines">
                            <table>
                                <thead>
                                    <tr>
                                        <th colspan="2" class="colspan">دارو‌ها</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for medicine in reservation.medicines.all %}
                                        <tr>
                                            <td>{{medicine.medicine.name}}</td>
                                            <td>{{medicine.how_to_use}}</td>
                                        </tr>
                                    {% empty %}
                                        <tr><td colspan="2" class="colspan">هیچ دارویی وجود ندارد</td></tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="timeline-card-description">
                        
                    </div>
                    {% include 'users/components/image_gallery.html' with images=reservation.images.all %}
                </div>
                <div class="action-buttons">
                    <a href="{% url 'clinic:new_service' reservation.id %}">سرویس جدید</a>
                    <a href="{% url 'clinic:new_image' reservation.id %}">تصویر جدید</a>
                    <a href="{% url 'clinic:new_medicine' reservation.id %}">داروی جدید</a>
                </div>
            </div>
        {% empty %}
            <p class="empty-result">هیچ سابقه درمانی وجود ندارد</p>
        {% endfor %}
        {% if reservations %}
            <div class="timeline-container">
                <div class="timeline-icon">
                    <i class="far fa-grin-beam-sweat"></i>
                </div>
                <div class="timeline-body" data-id={{reservation.id}}>
                    <h4 class="timeline-title"><span class="badge">شروع درمان</span></h4>
                </div>
            </div>
        {% endif %}
    </div>
</div>