apps/users/auth/urls.py
from django.urls import path
from django.contrib.auth import views as auth
from .views import StaffLoginView, StaffForgetPasswordView, StaffNewPasswordView

urlpatterns = [
    path('staff/login/', StaffLoginView.as_view(), name='staff_login'),
    path('staff/forgot-password/', StaffForgetPasswordView.as_view(), name='staff_forget_password'),
    path('staff/new-password/', StaffNewPasswordView.as_view(), name='password_reset_confirm'),
    path('logout/', auth.LogoutView.as_view(), name='account_logout'),
]

apps/users/urls.py
from django.urls import include, path
from apps.users.views import (
    DashboardView, ProfileUpdateView, PatientCreateView, PatientDetailView,
    PatientListView, PatientEditView, UserListView, UserUpdateView,
    UserCreateView, UserSetPasswordView,
)


app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('new/', UserCreateView.as_view(), name='new_user'),
    path('<pk>/update/', UserUpdateView.as_view(), name='update_user'),
    path('<pk>/set-password/', UserSetPasswordView.as_view(), name='set_password'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('profile/', DashboardView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='update_profile'),
    path('auth/', include('apps.users.auth.urls')),
    path('patients/', PatientListView.as_view(), name='patient_list'),
    path('patients/new/', PatientCreateView.as_view(), name='patient_create'),
    path('patients/<pk>/', PatientDetailView.as_view(), name='patient_details'),
    path('patients/<pk>/edit/', PatientEditView.as_view(), name='patient_edit'),
]

ghahri/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('d/admin/', admin.site.urls),
    path('clinic/', include('apps.clinic.urls')),
    path('core/', include('apps.core.urls')),
    path('users/', include('apps.users.urls')),
    path('auth/', include('apps.users.auth_urls')),
    path('api/', include('apps.clinic.api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/forms.py
from secrets import choice
from urllib import request
from django import forms
from django_filters import FilterSet
from django.contrib.auth import get_user_model
from apps.core import utils
from apps.core.models import CareerGroup, Career

User = get_user_model()


class UserForm(forms.ModelForm):
    password_confirm = forms.CharField(
        label='تکرار رمز عبور',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    password = forms.CharField(
        label='رمز عبور',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'mobile', 'role', 'avatar', 'password', 'password_confirm']

    def clean_mobile(self):
        mobile = self.cleaned_data['mobile']
        mobile = utils.persian_digits_to_english(mobile)
        return mobile

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise forms.ValidationError('رمز عبور باید حداقل 8 کاراکتر باشد')
        if password.isdigit():
            raise forms.ValidationError('رمز عبور نمیتواند تنها شامل عدد باشد')
        return password

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if not password:
            return password_confirm
        if password != password_confirm:
            raise forms.ValidationError('رمز عبور و تکرار آن باید یکسان باشد')
        return password_confirm

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['role'].widget.choices = self.remove_patient_from_roles(User.Roles.choices)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    @staticmethod
    def remove_patient_from_roles(choices):
        patient = (
            User.Roles.PATIENT.value,
            User.Roles.PATIENT.label,
        )
        choices.remove(patient)
        return choices


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        # fields = ['first_name', 'last_name', 'mobile', 'role', 'avatar']
        fields = ['first_name', 'last_name', 'role']

    # def clean_mobile(self):
    #     mobile = self.cleaned_data['mobile']
    #     mobile = utils.persian_digits_to_english(mobile)
    #     return mobile

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['role'].widget.choices = UserForm.remove_patient_from_roles(User.Roles.choices)
        self.fields['role'].widget = forms.HiddenInput()
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True


class UserSetPasswordForm(forms.ModelForm):
    current_password = forms.CharField(
        label='رمز عبور قبل',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    password_confirm = forms.CharField(
        label='تکرار رمز عبور',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    password = forms.CharField(
        label='رمز عبور',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(UserSetPasswordForm, self).__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = ['current_password', 'password', 'password_confirm']

    def clean_current_password(self):
        current_password = self.cleaned_data['current_password']
        if not self.user.check_password(current_password):
            raise forms.ValidationError('رمز عبور مطابقت ندارد')
        else:
            return current_password

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise forms.ValidationError('رمز عبور باید حداقل 8 کاراکتر باشد')
        if password.isdigit():
            raise forms.ValidationError('رمز عبور نمیتواند تنها شامل عدد باشد')
        return password

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if not password:
            return password_confirm
        if password != password_confirm:
            raise forms.ValidationError('رمز عبور و تکرار آن باید یکسان باشد')
        return password_confirm


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'avatar',)


class UserSignUpForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'mobile',)


class PatientFilterForm(FilterSet):
    class Meta:
        model = User
        fields = {
            'first_name': ['icontains'],
            'last_name': ['icontains'],
            'mobile': ['icontains'],
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.form.fields['first_name__icontains'].label = 'نام'
        self.form.fields['last_name__icontains'].label = 'نام خانوادگی'
        self.form.fields['mobile__icontains'].label = 'موبایل'


class PatientForm(forms.ModelForm):
    career_group = forms.ModelChoiceField(
        queryset=CareerGroup.objects.all(),
        required=False,
        empty_label='گروه شغلی',
        label='گروه شغلی'
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'mobile', 'national_code',
                  'career_group', 'career', 'birth_date', 'address', 'gender',
                  'marriage_status', 'phone_number', 'current_illness',
                  'current_medicines', 'treatment_history', 'notes')

    def clean_mobile(self):
        mobile = self.cleaned_data['mobile']
        mobile = utils.persian_digits_to_english(mobile)
        return mobile

apps/users/views.py
from urllib import request
from django.contrib.auth import update_session_auth_hash
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy as _
from django.views.generic import View, ListView, CreateView, UpdateView, TemplateView, FormView
from jalali_date import date2jalali, datetime2jalali
from apps.core.permissions import PermissionRequireMixin, Permissions
from apps.core.base import BaseContextMixin, GenericFormView, GenericModelFormView
from apps.core.mixins import CustomFormTemplateMixin, CustomListTemplateMixin
from .forms import (
    PatientForm, UserForm, PatientFilterForm, UserSignUpForm, UserProfileForm,
    UserUpdateForm, UserSetPasswordForm
)
User = get_user_model()


class DashboardView(LoginRequiredMixin, BaseContextMixin, View):
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return render(request, 'users/dashboard.html', context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ProfileUpdateView(LoginRequiredMixin, GenericModelFormView):
    model = User
    form_class = UserProfileForm
    template_name = 'generic_model_form.html'
    success_url = reverse_lazy('users:dashboard')
    success_message = 'اطلاعات شما با موفقیت بروزرسانی شد.'

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['extra_scripts'] = ['users/scripts/career_dropdown.js']
        return context

        
class UserListView(CustomListTemplateMixin, PermissionRequireMixin, ListView):
    permissions = [User.Roles.DOCTOR, User.Roles.ADMIN]
    page_title = 'لیست کاربران'
    queryset = User.objects.filter(role__in=[User.Roles.DOCTOR, User.Roles.SECRETARY, User.Roles.ADMIN])
    context_object_name = 'users'
    paginate_by = 100
    ordering = '-created_at'
    fields = ['username', 'first_name', 'last_name', 'role', 'created_at', 'last_login']
    header_buttons = [{'title': 'افزودن کاربر', 'url': reverse_lazy('users:new_user')}]
    action_buttons = [
        {'title': 'ویرایش', 'url_name': 'users:update_user', 'arg_field': 'id',
         'fa-icon': 'fa-edit', 'class': '', 'class_form_field': 'id'},
        {'title': 'تغییر رمز', 'url_name': 'users:set_password', 'arg_field': 'id',
         'fa-icon': 'fa-edit', 'class': 'btn-warning', 'class_form_field': 'id'},
    ]

    def get_role(self, obj):
        return obj.get_role_display()

    def get_created_at(self, obj):
        return datetime2jalali(obj.created_at).strftime('%Y/%m/%d %H:%M:%S')

    def get_last_login(self, obj):
        last_login = obj.last_login
        if last_login:
            return datetime2jalali(last_login).strftime('%Y/%m/%d %H:%M:%S')
        return '-'


class UserCreateView(CustomFormTemplateMixin, PermissionRequireMixin, CreateView):
    permissions = [User.Roles.DOCTOR, User.Roles.ADMIN]
    model = User
    form_class = UserForm
    page_title = 'افزودن کاربر جدید'
    success_url = reverse_lazy('users:user_list')
    cancel_url = reverse_lazy('users:user_list')
    success_message = ' کاربر جدید با موفقیت ثبت شد.'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.username = user.mobile
        user.save()
        return super().form_valid(form)



class UserUpdateView(UserCreateView, UpdateView):
    page_title = 'ویرایش کاربر'
    success_message = 'کاربر با موفقیت ویرایش شد.'
    form_class = UserUpdateForm

    def get_success_url(self) -> str:
        return reverse_lazy('clinic:clinic')

    def get_queryset(self):
        return User.objects.filter(pk=self.request.user.id)


class UserSetPasswordView(CustomFormTemplateMixin, PermissionRequireMixin, FormView):
    model = User
    form_class = UserSetPasswordForm
    success_url = reverse_lazy('clinic:clinic')
    success_message = 'رمز عبور با موفقیت بروزرسانی شد.'
    page_title = 'تغییر رمز عبور'

    def get_form_kwargs(self):
        kwargs = super(UserSetPasswordView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def get_page_subtitle(self):
        user = self.get_object()
        return user.get_full_name()      

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return get_object_or_404(User, pk=pk)
    
    def form_valid(self, form):
        user = self.get_object()
        user.set_password(form.cleaned_data['password'])
        update_session_auth_hash(self.request, user)
        user.save()
        return super().form_valid(form)


class PatientCreateView(CustomFormTemplateMixin, PermissionRequireMixin, CreateView):
    permissions = [User.Roles.SECRETARY, User.Roles.DOCTOR, User.Roles.ADMIN]
    model = User
    form_class = PatientForm
    success_url = reverse_lazy('users:patient_list')
    success_message = 'اطلاعات با موفقیت ثبت شد.'
    page_title = 'افزودن پرونده جدید'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['extra_scripts'] = ['users/scripts/career_dropdown.js']
        return context

    def form_valid(self, form):
        form.instance.role = User.Roles.PATIENT
        messages.success(self.request, self.success_message)
        return super().form_valid(form)


class PatientEditView(CustomFormTemplateMixin, PermissionRequireMixin, UpdateView):
    permissions = [User.Roles.SECRETARY, User.Roles.DOCTOR, User.Roles.ADMIN]
    model = User
    form_class = PatientForm
    success_url = reverse_lazy('users:patient_list')
    success_message = 'اطلاعات با موفقیت بروزرسانی شد.'
    page_title = 'ویرایش پرونده'

    def form_valid(self, form):
        messages.success(self.request, self.success_message)
        return super().form_valid(form)


class PatientListView(CustomListTemplateMixin, PermissionRequireMixin, ListView):
    permissions = [User.Roles.SECRETARY, User.Roles.DOCTOR, User.Roles.ADMIN]
    template_name = 'generic_model_list.html'
    context_object_name = 'patients'
    page_title = "لیست بیماران"
    fields = ['first_name', 'last_name', 'mobile', ]
    header_buttons = [
        {'title': 'افزودن بیمار', 'url': reverse_lazy('users:patient_create'), 'fa-icon': 'fa-plus', 'class': 'btn-success'},
    ]
    action_buttons = [
        {'title': 'مشاهده پرونده', 'url_name': 'users:patient_details', 'arg_field': 'id',
         'fa-icon': 'fa-list', 'class': '', 'class_form_field': 'id'},
        {'title': 'ویرایش', 'url_name': 'users:patient_edit', 'arg_field': 'id',
         'fa-icon': 'fa-list', 'class': '', 'class_form_field': 'id'},
    ]
    paginate_by = None
    filter_class = PatientFilterForm

    def get_queryset(self):
        objects = User.objects.filter(role=User.Roles.PATIENT)
        filtered_objects = self.filter_class(self.request.GET, queryset=objects)
        return filtered_objects.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class PatientDetailView(PermissionRequireMixin ,TemplateView):
    permissions = [User.Roles.DOCTOR, User.Roles.ADMIN, User.Roles.SECRETARY]
    template_name = 'users/patient_detail_view.html'
    context_object_name = 'patient'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        patient = get_object_or_404(User, id=kwargs['pk'])
        context["patient"] = patient
        return context

apps/users/templates/users/dashboard.html
{% extends 'base.html' %}
{% load static jalali_tags %}

{% block extra_head %}
  <script src="{% static 'js/gauge.min.js' %}"></script>
{% endblock extra_head %}

{%block page_content%}
<div class="row" style="display: flex">
  <div class="col-md-8 col-sm-8 col-xs-12 equal-height-parent">
    <div class="x_panel">
      <div class="x_title">
        <h2>
          صفحه پروفایل کاربر
          <small>#{{user.id}}</small>
        </h2>
        <ul class="nav navbar-right panel_toolbox">
          <li>
            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <div class="col-md-3 col-sm-3 col-xs-12 profile_left">
          <div class="profile_img">
            <div id="crop-avatar">
              <img
                class="img-responsive avatar-view"
                src="{{user.avatar_url}}"
                alt="{{user.display_name}}"
                title="Change the avatar"
              />
            </div>
          </div>
          <h3 class="text-3xl my-4 font-medium">{{user.display_name}}</h3>
          <ul class="list-unstyled user_data">
            <li class="m-top-xs">
              <i class="fa fa-list-alt"></i>
              {{user.national_code|default:'کد ملی تنظیم نشده'}}
            </li>
            <li class="m-top-xs">
              <i class="fa fa-user"></i>
              کد معرف: 
              {{user.referral_code|default:'کد معرف تنظیم نشده است'}}
            </li>
            <li class="m-top-xs">
              <i class="fa fa-envelope"></i>
              {{user.email|default:'آدرس ایمیل تنظیم نشده'}}
            </li>
            <li class="m-top-xs">
              <i class="fa fa-phone"></i>
              {{user.mobile}}
            </li>
          </ul>
          <a class="btn btn-success" href={% url 'users:update_profile' %}
            ><i class="fa fa-edit m-right-xs"></i>&nbsp;ویرایش پروفایل</a
          >
          <br />
        </div>
        <div class="col-md-9 col-sm-9 col-xs-12">
          <div class="" role="tabpanel" data-example-id="togglable-tabs">
            <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
              <li role="presentation" class="active">
                <a
                  href="#tab_content1"
                  id="home-tab"
                  role="tab"
                  data-toggle="tab"
                  aria-expanded="true"
                  >فعالیت اخیر</a
                >
              </li>
              <li role="presentation" class="">
                <a
                  href="#tab_content2"
                  role="tab"
                  id="profile-tab"
                  data-toggle="tab"
                  aria-expanded="false"
                  >پروژه مشغول به کار</a
                >
              </li>
              <li role="presentation" class="">
                <a
                  href="#tab_content3"
                  role="tab"
                  id="profile-tab2"
                  data-toggle="tab"
                  aria-expanded="false"
                  >پروفایل</a
                >
              </li>
            </ul>
            <div id="myTabContent" class="tab-content">
              <div
                role="tabpanel"
                class="tab-pane fade active in"
                id="tab_content1"
                aria-labelledby="home-tab"
              >
                
              </div>
              <div
                role="tabpanel"
                class="tab-pane fade"
                id="tab_content2"
                aria-labelledby="profile-tab"
              >
                <table class="data table table-striped no-margin">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>نام پروژه</th>
                      <th>شرکت مشتری</th>
                      <th class="hidden-phone">ساعت صرف شده</th>
                      <th>مشارکت</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>1</td>
                      <td>New Company Takeover Review</td>
                      <td>Deveint Inc</td>
                      <td class="hidden-phone">18</td>
                      <td class="vertical-align-mid">
                        <div class="progress">
                          <div
                            class="progress-bar progress-bar-success"
                            data-transitiongoal="35"
                            aria-valuenow="35"
                            style="width: 35%"
                          ></div>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td>2</td>
                      <td>New Partner Contracts Consultanci</td>
                      <td>Deveint Inc</td>
                      <td class="hidden-phone">13</td>
                      <td class="vertical-align-mid">
                        <div class="progress">
                          <div
                            class="progress-bar progress-bar-danger"
                            data-transitiongoal="15"
                            aria-valuenow="15"
                            style="width: 15%"
                          ></div>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td>3</td>
                      <td>Partners and Inverstors report</td>
                      <td>Deveint Inc</td>
                      <td class="hidden-phone">30</td>
                      <td class="vertical-align-mid">
                        <div class="progress">
                          <div
                            class="progress-bar progress-bar-success"
                            data-transitiongoal="45"
                            aria-valuenow="45"
                            style="width: 45%"
                          ></div>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td>4</td>
                      <td>New Company Takeover Review</td>
                      <td>Deveint Inc</td>
                      <td class="hidden-phone">28</td>
                      <td class="vertical-align-mid">
                        <div class="progress">
                          <div
                            class="progress-bar progress-bar-success"
                            data-transitiongoal="75"
                            aria-valuenow="75"
                            style="width: 75%"
                          ></div>
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div
                role="tabpanel"
                class="tab-pane fade"
                id="tab_content3"
                aria-labelledby="profile-tab"
              >
                <p>
                  در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه
                  راهکارها و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل
                  حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای
                  موجود طراحی اساسا مورد استفاده قرار گیرد. در این صورت می توان
                  امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت
                  تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای
                  اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد
                  استفاده قرار گیرد.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4 col-sm-4 col-xs-12 equal-height-child">
    <div class="x_panel">
      <div class="x_title">
        <h2>
          کد معرف
        </h2>
        <ul class="nav navbar-right panel_toolbox">
          <li>
            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content" style="text-align: center;">
        <div class="sidebar-widget">
          <small>کد معرف شما برای دعوت دوستان</small>
          <div class="clipboard-box" onclick="copyToClipboard('{{user.referral_code}}')">
            <div class="clipboard-body"><h4>{{user.referral_code}}</h4></div>
            <div class="clipboard-button">
              <i class="fa fa-copy"></i>
            </div>
          </div>
          <small>در صورتی که ده معرفی موفق داشته باشید،‌ ....</small>
            <canvas width="160" height="100" id="referral_code_gauge"
                    style="width: 160px; height: 100px; margin: 0px auto;">

            </canvas>
            <div class="goal-wrapper">
              <span id="gauge-text" class="gauge-value pull-left">
                تعداد افراد دعوت شده: {{user.total_referred_users}}</span>
              <span id="goal-text" class="goal-value pull-right">
                تعداد مورد نیاز تا سطح بعد: 10</span>
            </div>
          </div>
          <table class="table table-bordered" style="margin-top: 20px;">
            <thead>
              <tr>
                <th style="text-align: center" colspan="3">افراد دعوت شده</th>
              </tr> 
            </thead>
            <tbody>
              {% for referral in user.referrals.all %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ referral.referred.display_name }}</td>
                  <td>{{ referral.created_at|to_jalali:"%Y/%m/%d" }}</td>
                </tr>
              {% empty %}
                <tr>
                  <td colspan="3">تابحال کسی را دعوت نکرده اید</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
      </div>
    </div>
  </div>
</div>
{%endblock page_content%}

{% block extra_scripts %}
  <script>
    var options = {
      lines:12,
      angle:0, 
      lineWidth:.4, 
      pointer: { 
        length:.75,
        strokeWidth:.042,
        color:"#1D212A"
      },
      limitMax:"false",
      colorStart:"#1ABC9C",
      colorStop:"#1ABC9C",
      strokeColor:"#F0F3F3",
      generateGradient:!0,
      maxValue:80
    }
    var target = document.getElementById('referral_code_gauge');
    var gauge = new Gauge(target).setOptions(options);
    gauge.maxValue = 10;
    gauge.setMinValue(0);
    gauge.animationSpeed = 32;
    gauge.set({{user.total_referred_users}});

    function copyToClipboard(text) {
      navigator.clipboard.writeText(text);
      showInfoMessage("کد معرف شما در حافظه کپی شد");
    }
  </script>
{% endblock %}